name: Publish

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
         node-version: 18.x

    - name: Install dependencies
      run: npm install

    - name: Publish extension
      run: npm run deploy
      env:
        VSCE_PAT: ${{ secrets.VSC_WVIEWS_SECRET }}

    - name: Bump version
      run: npm version patch

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v1
      with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Bump version
          title: Bump version